### ISSUE TITLE
sls encrypt console command not working (no response in console)

### ISSUE THREAD

**Issue by doubleminus** [nordcloud/serverless-kms-secrets#21] opened 2019-01-09 00:43 UTC
When attempting a command like so: `sls encrypt --stage dev -n SECRETS_KEY:SECRETS_VALUE -v password -k 1234-5678-9123-123 --aws-profile profileName` we are receiving no reply back from the console. This is on MacOS in a bash terminal. Running latest version of serverless globally (v1.35.1) and as a dev dependency in our node project (using node 8.10.0).

After some investigation, the problem seems to be occurring on line 71 in the index.js (https://github.com/nordcloud/serverless-kms-secrets/blob/master/index.js). The encryptVariable function is never called in the .then block.

Do you have any advice/guidance?

**Comment by simonbbrown** [comment] 2019-01-10 22:31
I am also having this issue and has me dead in the water as I depend on this plugin for configuration! Please help!

**Comment by simonbbrown** [comment] 2019-01-11 01:45
@doubleminus I was able to manually get around the issue by encrypting via command line and updating the environment file. Heres the command I did:

aws kms encrypt --key-id 'KEYARN' --plaintext 'TEXT' --profile default --region 'myregion'

Hope that helps in the meanwhile!

**Comment by jbrunken** [comment] 2019-01-27 22:46
I had this problem after upgrading serverless.

In order to get around it, I had to downgrade to Node 8.10 and Serverless v1.27.0

**Comment by jbrunken** [comment] 2019-01-27 23:01
After a bit more investigation, something seems to have broken with the 1.33.0 release of serverless.

I'm able to run encrypt/decrypt with 1.32.0, but 1.33.0 breaks in both node 8 & 10.

**Comment by michael-misshore** [comment] 2019-02-13 12:34
+1 We're also having this issue. If I can get some free time, I might start to dig into/fix this.

**Comment by mpuittinen** [comment] 2019-02-13 12:41
The issue is most probably the same than we encountered with serverless-mocha-plugin. Have been superbusy so have not had time to apply the fix yet.

**Comment by localredhead** [comment] 2019-02-13 18:58
+1 Seeing this issue

**Comment by ajunge** [comment] 2019-02-20 15:50
@mpuittinen If you point me to the fix in serverless-mocha-plugin I can try a PR to fix this one

**Comment by mpuittinen** [comment] 2019-02-24 10:42
This should now be fixed in 1.0.4 (published to npm)

**Closed by mpuittinen** 2019-02-24 10:42 UTC
